Bil 498 textfield 2
Billes/poff-components pull request #16
Opened 2022-12-12 07:54 UTC by Molnet2013

2022-12-12 08:24 UTC, bjorkgard requested changes
Det ser bra ut men det är några småsaker som behöver justeras innan vi är helt klara.

2022-12-12 08:24 UTC, bjorkgard commented on src/components/Textarea/Textarea.tsx
> +        rows={5}
Rows bör vara en variabel som man kan sätta via en props. Default-värdet på denna props skall vara 5.

2022-12-12 08:24 UTC, bjorkgard commented on src/components/Textarea/Textarea.types.ts
> +export interface TextareaProps {
Typen för rows behöver vara med här

2022-12-12 08:24 UTC, bjorkgard commented on src/components/Textarea/Textarea.tsx
> +        {...props}
Disabled finns som en props. Men den används inte på textarean.
Sätt in `disabled={disabled}` på textarea-taggen (någonstans mellan rad 23-26) så blir det korrekt.

2022-12-12 08:24 UTC, bjorkgard commented on src/stories/Textarea.stories.tsx
> +Default.args = { placeholder: 'testar med text' }
Gör gärna några fler stories (kopiera rad 12 & 13) med andra args
- En version där textarean är disabled
- En version med 10 rader hög textarea

2022-12-13 12:18 UTC, Molnet2013 commented on src/components/Textarea/Textarea.tsx
> +        {...props}
Done

2022-12-13 12:53 UTC, bjorkgard approved these changes

2022-12-13 12:54 UTC, Molnet2013 commented
merging

2022-12-13 12:54 UTC, merged

2022-12-13 12:55 UTC, bjorkgard commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@billes-tryckeri/poff-components/v/1.1.0)
- [GitHub release](https://github.com/Billes/poff-components/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: